
export default {
  GET_ALL_TOPICS: "TOPICS/GET_ALL",
  ADD_TOPIC: "TOPICS/ADD_ITEM",
  ADD_TOPICS: "TOPICS/ADD_ITEMS",
  SET_TOPICS: "TOPICS/SET_ITEMS",
  SET_TOPIC_BASE: "TOPICS/SET_BASE",
  SET_TOPIC_TREE: "TOPICS/SET_TREE"
};